apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deimos-clusterRoleBinding
subjects:
- kind: ServiceAccount
  name: deimos-serviceaccount
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: deimos
  apiGroup: rbac.authorization.k8s.io
